### ISSUE TITLE
Unstaked adresses are not recognoized

### ISSUE THREAD

**Issue by cardano-nft** [PaskLab/adastry-ui#7]
If I add unskated adresses they are not recognoized. Of course there is no reward history to export but I would like to export the transaction history of some of my unstaked Nami accounts.

**Comment by pascallapointe** [comment]
Yes support for unstaked address would be great. The project didn't aimed for this at first since it was meant for Armada Alliance delegated wallet only.

Will add support for them along with support for wallet delegated to external pools.
This feature might take a few months to be properly added regarding my current schedule, i'm leaving this issue opened until then.

Thanks for theses valuable feedback

**Comment by pascallapointe** [comment]
Posponed, will review possibilities later this year.

The system currently track stake addresses, not single addresses.
This feature would require a different mechanic.

At the exception of NamiWallet which is using a single address, it is impossible for our system to establish the link between all addresses link to an unregistered stake credential.

There would be ways to let a user manually connect his wallet and import all **"used addresses"**, but the process would have to be done everytime a user use a new address to get the right outcome 🤔

I can see the value of such feature to keep some privacy on the public front.

**Comment by pascallapointe** [comment]
Support for unregistered addresses added.
